"""empty message

Revision ID: 0454196780d6
Revises: fa0384aa8f03
Create Date: 2023-04-25 17:01:09.265410

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0454196780d6'
down_revision = 'fa0384aa8f03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('phone_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', mysql.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###
