"""empty message

Revision ID: 08ec87295e8a
Revises: 2bcef0f4a72f
Create Date: 2023-05-03 11:32:31.991723

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '08ec87295e8a'
down_revision = '2bcef0f4a72f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('album', schema=None) as batch_op:
        batch_op.drop_column('broad_location')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('album', schema=None) as batch_op:
        batch_op.add_column(sa.Column('broad_location', mysql.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###
