"""empty message

Revision ID: 13daa0f1b24a
Revises: 9083c365456c
Create Date: 2023-05-05 16:18:34.178355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13daa0f1b24a'
down_revision = '9083c365456c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.drop_column('data')

    # ### end Alembic commands ###
