"""empty message

Revision ID: 1ee13d0c8bb2
Revises: 73fd909ea48d
Create Date: 2023-04-29 20:42:33.513755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ee13d0c8bb2'
down_revision = '73fd909ea48d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('album', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_trip', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('cover_image', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'photo', ['cover_image'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('album', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('cover_image')
        batch_op.drop_column('current_trip')

    # ### end Alembic commands ###
