"""empty message

Revision ID: 2bcef0f4a72f
Revises: effb13ae14a4
Create Date: 2023-05-03 11:30:37.856224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bcef0f4a72f'
down_revision = 'effb13ae14a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('album', schema=None) as batch_op:
        batch_op.add_column(sa.Column('broad_location', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('album', schema=None) as batch_op:
        batch_op.drop_column('broad_location')

    # ### end Alembic commands ###
