"""empty message

Revision ID: 41c80d89a428
Revises: b2da1779a9b9
Create Date: 2023-04-28 12:59:59.834753

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '41c80d89a428'
down_revision = 'b2da1779a9b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('album', schema=None) as batch_op:
        batch_op.drop_column('all_days_in_same_region_or_state')
        batch_op.drop_column('region_or_state')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('album', schema=None) as batch_op:
        batch_op.add_column(sa.Column('region_or_state', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('all_days_in_same_region_or_state', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
