"""empty message

Revision ID: 6e18341348b5
Revises: 827883086b5f
Create Date: 2023-04-25 14:22:56.395281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e18341348b5'
down_revision = '827883086b5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('album', schema=None) as batch_op:
        batch_op.add_column(sa.Column('all_days_in_same_country', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('all_days_in_same_region_or_state', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('all_days_in_same_city', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('album', schema=None) as batch_op:
        batch_op.drop_column('all_days_in_same_city')
        batch_op.drop_column('all_days_in_same_region_or_state')
        batch_op.drop_column('all_days_in_same_country')

    # ### end Alembic commands ###
