"""empty message

Revision ID: 9083c365456c
Revises: 28c5af6c71b1
Create Date: 2023-05-05 13:33:48.838250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9083c365456c'
down_revision = '28c5af6c71b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('album', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover_image', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'photo', ['cover_image'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('album', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('cover_image')

    # ### end Alembic commands ###
