"""empty message

Revision ID: b2da1779a9b9
Revises: 3adbf9d74ed6
Create Date: 2023-04-25 21:49:12.466631

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b2da1779a9b9'
down_revision = '3adbf9d74ed6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.add_column(sa.Column('friend_without_user_id', sa.String(length=255), nullable=True))
        batch_op.drop_column('friend_first_name')
        batch_op.drop_column('friend_last_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.add_column(sa.Column('friend_last_name', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('friend_first_name', mysql.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('friend_without_user_id')

    # ### end Alembic commands ###
