"""empty message

Revision ID: b4a807d35b7e
Revises: 0cee7e46b900
Create Date: 2023-05-01 20:41:21.896542

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b4a807d35b7e'
down_revision = '0cee7e46b900'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photo', schema=None) as batch_op:
        batch_op.drop_column('filename')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filename', mysql.VARCHAR(length=255), nullable=False))

    # ### end Alembic commands ###
