"""empty message

Revision ID: bb2e18479089
Revises: 34b31c95eaf5
Create Date: 2023-05-08 00:47:42.933361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb2e18479089'
down_revision = '34b31c95eaf5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('album', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover_image', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'photo', ['cover_image'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('album', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('cover_image')

    # ### end Alembic commands ###
