"""empty message

Revision ID: effb13ae14a4
Revises: b4a807d35b7e
Create Date: 2023-05-02 10:22:46.282209

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'effb13ae14a4'
down_revision = 'b4a807d35b7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filename', sa.Text(), nullable=False))
        batch_op.drop_column('file_location')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_location', mysql.TEXT(), nullable=False))
        batch_op.drop_column('filename')

    # ### end Alembic commands ###
